/* (c) https://github.com/MontiCore/monticore */
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent


plugins {
    id 'java'
    id "maven-publish"
    id "io.github.themrmilchmann.ecj" version "0.2.0" apply false
    id "de.se_rwth.codestyle" version "$mc_version"
}



description = "BPMN-DSL"

allprojects {
    group 'de.monticore.lang'
    layout.buildDirectory = layout.projectDirectory.dir("target")

    repositories {
        if (("true").equals(getProperty('useLocalRepo'))) {
            mavenLocal()
        }
        maven {
            credentials.username mavenUser
            credentials.password mavenPassword
            url repo
        }
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.github.themrmilchmann.ecj'
    apply plugin: 'maven-publish'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
    ecj {
        compilerVersion = "3.43.0"
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        testLogging {
            // controls whether test output is shown
            showStandardStreams = !("false").equals(getProperty('showTestOutput'))
            showExceptions true
            showCauses true
            showStackTraces true
            exceptionFormat TestExceptionFormat.FULL
            info {
                events TestLogEvent.FAILED,
                        TestLogEvent.PASSED,
                        TestLogEvent.SKIPPED,
                        TestLogEvent.STANDARD_OUT
            }
        }
        afterTest { desc, result ->
            logger.lifecycle "${desc.className} > ${desc.name} ${result.resultType}"
        }
        afterSuite { desc, result ->
            if (!desc.parent) { // will match the outermost suite
                def output = "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} passed, ${result.failedTestCount} failed, ${result.skippedTestCount} skipped)"
                def startItem = '|  ', endItem = '  |'
                logger.lifecycle startItem + output + endItem
            }
        }
        reports {
            junitXml.required = true
            html.required = false
        }
    }

    tasks.withType(JavaCompile).tap {
        configureEach {
            options.encoding = "UTF-8"
            options.deprecation false
            options.warnings = false
            options.forkOptions.jvmArgs += ["-Xmx4G"]
            // TODO: reevaluate with new ecj plugin
            outputs.cacheIf { false } // ECJ has problem with caching
        }
    }
}

/**
 * Builds the whole BPMN project
 * Executes JUnit tests and assembles the jars
 */
tasks.register('buildBPMN') {
    group("build")
    description("Builds the whole BPMN project, i.e. BpmnXML, TimerConditions, WorkflowCLI and WorkflowDSL")
    dependsOn(
            ":WorkflowCLI:build",
            ":WorkflowConformance:build",
            ":WorkflowDSL:build",
            gradle.includedBuilds*.task(":build")
    )
}

/**
 * Executes JUnit tests for the BPMN project
 */
tasks.register('testBPMN') {
    group("verification")
    description("Tests the JUnit Tests in the BPMN project")
    dependsOn(
            ":WorkflowCLI:test",
            ":WorkflowConformance:test",
            ":WorkflowDSL:test",
            gradle.includedBuilds*.task(":test")
    )
}

/**
 *  Publishes the jars of the BPMN projects to the nexus repository.
 *  Assembles the jars and publishes them, but does not execute JUnit tests.
 */
tasks.register('publishBPMN') {
    group("publishing")
    description('Publishes the BPMN projects')

    dependsOn(
            ":WorkflowCLI:publish",
            ":WorkflowDSL:publish",
            gradle.includedBuilds*.task(":publish")
    )
}

/**
 *  Publishes the jars of the BPMN project
 *  to the local m2 repository. Typically this should not be needed.
 *  Assembles the jars and publishes them, but does not execute JUnit tests.
 */
tasks.register('publishBPMNToMavenLocal') {
    group("publishing")
    description('Publishes the BPMN projects' +
            'to the local maven repository.')
    dependsOn(
            ":WorkflowCLI:publishToMavenLocal",
            ":WorkflowDSL:publishToMavenLocal",
            gradle.includedBuilds*.task(':publishToMavenLocal')
    )
}

tasks.register('buildAll', GradleBuild) {
    dependsOn(subprojects.collect { getTasksByName("build", false) })
}

tasks.register('cleanBPMN') {
    group("build")
    dependsOn(
            ":WorkflowCLI:clean",
            ":WorkflowConformance:clean",
            ":WorkflowDSL:clean"
    )
}

configure([
           project(':WorkflowCLI'),
           project(':WorkflowDSL')
]){
    apply plugin: 'maven-publish'

    // configure deployment
    publishing {
        publications {
            maven(MavenPublication) {
                from(components.java)
            }
        }
        repositories.maven {
            credentials.username mavenUser
            credentials.password mavenPassword
            def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/"
            def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
        }
    }
}

defaultTasks 'build'
