mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
useLocalRepo=false
showTestOutput=false

SE_Nexus_ID=SE-nexus
releasesRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/
snapshotsRepoUrl=https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/

grammars_classifier=grammars

version=7.9.0-SNAPSHOT
mc_version=7.9.0-SNAPSHOT
ocl_version=7.9.0-SNAPSHOT
se_commons_version=7.9.0-SNAPSHOT
petrinets_version=7.9.0-SNAPSHOT
exec_version=1.11
gson_version=2.10.1
guava_version=33.5.0-jre
joda_time_version=2.10.4
jgrapht_version=1.3.1
picoli_version=4.1.0
jaxb_api_version=2.3.1
jaxb_core_version=2.3.0.1
jaxb_impl_version=2.3.2
logback_version=1.2.3
jsr305_version=3.0.2
junit_jupiter_version=5.8.2
cron_utils_version=9.1.6
shadow_version=8.3.9
