/* (c) https://github.com/MontiCore/monticore */
plugins {
    id 'java'
    id "jacoco"
    id "de.se_rwth.codestyle" version "$mc_version"
}

group = 'de.monticore.conformance'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':WorkflowDSL')

    implementation "org.jgrapht:jgrapht-core:$jgrapht_version"
    implementation "org.tinyjee.jgraphx:jgraphx:$jgraphx_version"
    implementation "org.jgrapht:jgrapht-ext:$jgrapht_version"

    implementation project(":WorkflowDSL")
    implementation "de.monticore:monticore-runtime:$mc_version"
    implementation "de.monticore:monticore-grammar:$mc_version"

    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_jupiter_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_jupiter_version"
}

test {
    useJUnitPlatform()
}
